### ISSUE TITLE
Exception: Directory already exists: ../out/mhqg-wq/graph2seq

### ISSUE THREAD

**Issue by luyi6111** [hugochan/Graph2Seq-for-KGQG#2]
In fact, the directory doesn't exist. I don't know why.

Traceback (most recent call last):
  File "./src/main.py", line 144, in <module>
    main(config)
  File "./src/main.py", line 23, in main
    model = ModelHandler(config)
  File "/home/Graph2Seq-for-KGQG/src/core/model_handler.py", line 45, in __init__
    self.logger = DummyLogger(config, dirname=config['out_dir'], pretrained=config['pretrained'])
  File "/home/Graph2Seq-for-KGQG/src/core/utils/logger.py", line 17, in __init__
    raise Exception('Directory already exists: {}'.format(dirname))
Exception: Directory already exists: ../out/mhqg-wq/graph2seq

**Comment by luyi6111** [comment]
> In fact, the directory doesn't exist. I don't know why.
> 
> Traceback (most recent call last):
> File "./src/main.py", line 144, in
> main(config)
> File "./src/main.py", line 23, in main
> model = ModelHandler(config)
> File "/home/Graph2Seq-for-KGQG/src/core/model_handler.py", line 45, in **init**
> self.logger = DummyLogger(config, dirname=config['out_dir'], pretrained=config['pretrained'])
> File "/home/Graph2Seq-for-KGQG/src/core/utils/logger.py", line 17, in **init**
> raise Exception('Directory already exists: {}'.format(dirname))
> Exception: Directory already exists: ../out/mhqg-wq/graph2seq

已解决
